### ISSUE TITLE
feat: Allow adding stages to run builds for things like compiled programs

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#108]
I've been thinking of this idea for a while now and I've heard from one of our users that they would like to do something similar. So now that we've proven that multi-stage builds will work for us, we can take advantage of that to allow users to create their own stages. This would be useful for compiling software that might require a specific set of dependencies that you don't want in your final image. 

### Spec

For creating a stage, I thought that the best way to represent a set of stages was to add a `stages` property in the top level of the file. Here you have a list of stages with the required properties of `name`, `image`, and `modules`. The user would then be able to add modules to call from within the stage. In the example below, I'm using the `containerfile` module to build `bluebuild` using `cargo` on the `rust` image. Then in the main modules, I'm using `COPY` to copy the bin into the final image without having to install all of the `cargo` dependencies in my final image.

```yaml
name: jp-desktop
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable
description: The image of Wunker OS for JP's desktop.
blue-build-tag: main-installer
stages:
  - name: blue-build
    image: rust
    modules:
      - type: containerfile
        snippets:
          - |
            RUN cargo install blue-build --features nightly --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/bluebuild /out/bluebuild
modules:
  - type: containerfile
    snippets:
      - COPY --from=blue-build /out/bluebuild /usr/bin/bluebuild
```

The resulting `Containerfile` would end up looking something like this:

```dockerfile
# ...
FROM rust as blue-build
RUN cargo install blue-build --features nightly --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/bluebuild /out/bluebuild

FROM ghcr.io/ublue-os/bazzite-nvidia

# ...
COPY --from=blue-build /out/bluebuild /usr/bin/bluebuild
```

Adding support for `from-file:` would also make this extremely modular and allow for easy reuse. It can follow the same patter where it could be a single stage:

```yaml
name: blue-build
image: rust
modules:
  - type: containerfile
    snippets:
      - |
        RUN cargo install blue-build --features nightly --target x86_64-unknown-linux-gnu \
          && mkdir -p /out/ \
          && mv $CARGO_HOME/bin/bluebuild /out/bluebuild
```

Or it can hold multiple ones

```yaml
stages:
  - name: blue-build
    image: rust
    modules:
      - type: containerfile
        snippets:
          - |
            RUN cargo install blue-build --features nightly --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/bluebuild /out/bluebuild
  - name: cargo-release
    image: rust
    modules:
      - type: containerfile
        snippets:
          - |
            RUN cargo install cargo-release --locked --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/cargo-release /out/cargo-release
```
