### ISSUE TITLE
feat: Add Jsonnet support for matrix based building

### ISSUE THREAD

**Issue by gmpinder** [blue-build/cli#140]
So there was some conversation in discord and some in a [discussion](https://github.com/orgs/blue-build/discussions/5) about trying to have support for a recipe building multiple versions of itself. For example @qoijjj has mentioned that it would be much easier to support the transition of [SecureBlue](https://github.com/secureblue/secureblue) to Fedora 40 if all that needed to be done was to mark each recipe to build both a `39` version and a `40` version.

My proposal is to allow the existing `image-version` property in the top level to accept both a single value and an array of values. This would allow existing recipes to continue working and allow scaling up builds. So an example recipe could look something like this:

```yaml
name: cli/test
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-surface
image-version:
  - 40
  - 39
modules:
  - from-file: akmods.yml
```

The CLI would then go through and build 2 separate images, one based on 39 and one on 40. All tags that are currently created contain the version of Fedora that built except `latest`. In this instance, we would set `latest` to the highest version that is being built. This could also open the door to supporting a `gts` tag for the second highest version. 

Now there is a possibility that there will be recipe's that have module definitions that make it incompatible across versions. At this point, it would be up to the user to separate out the recipes and manage these changes. Or we can support having a `for-version` or some property for each module that makes it so that you can cordon certain modules to only be ran on a specific version. Like:

```yaml
modules:
  - type: rpm-ostree
    for-version: 40
    install:
      - binutils
 ```

**Comment by xynydev** [comment]
The main issue here is that building multiple versions of an image with the same name is not possible with the current tagging system, which always assigns the `latest` tag to the currently building image. 

I see two ways to add support for multi-version images. These are not mutually incompatible, but can be used to achieve the same thing.

I think we should either do both A&B, or just B, but not A alone. I'm not sure if option A would be required to support this fully, or even desirable due to its drawbacks. 

## A.
(originally from @gmpinder)
```yml
# recipe.yml
image-version: [38, 39]
```
- automatically build multiple versions from a single recipe
- break 1-1 correspondence with recipes to images
   - issue with template/generate command now generating two containerfiles
- easier to configure
- no way to have separate configuration for different versions, unless a clunky syntax like `for-version` as proposed above is used

## B.
(originally from @gerblesh)
```yml
# recipe-gts.yml
image-version: 38
image-tags: [gts] # replaces the 'latest' tag
```
```yml
# recipe-current.yml
image-version: 39
# 'latest' tag is applied by default
```
- use multiple recipes to build different versions of the same image
- keeps 1-1 correspondence with recipes to images
- a bit harder to set up, need to import the modules from a separate file to keep the configs same
- very easy to configure different things for different images
- opens up the possibility to tag images in a multitude of ways, like `gts`
