### ISSUE TITLE
bug: Fedora distrobox image doesn't setup userspace with docker properly

### ISSUE THREAD

**Issue by michaelhaaf** [blue-build/cli#145]
#### Current Behavior

The last several times I have run a successful `bluebuild build <recipe>` command, the process ends with something like following behavior (in this case, the image name is `combined-nvidia`):

```
[2024-03-29T20:49:37Z INFO  blue_build::commands::build] --> 29330c35fdcc
[2024-03-29T20:49:37Z INFO  blue_build::commands::build] [5/5] STEP 29/29: LABEL "org.blue-build.build-id"="3fcf8459-9de7-4929-b421-2f731770a1b4"
[2024-03-29T20:49:37Z INFO  blue_build::commands::build] [5/5] COMMIT combined-nvidia:local-39
[2024-03-29T20:49:38Z INFO  blue_build::commands::build] --> c4466ebead8a
[2024-03-29T20:49:38Z INFO  blue_build::commands::build] Successfully tagged localhost/combined-nvidia:local-39
[2024-03-29T20:49:50Z INFO  blue_build::commands::build] c4466ebead8a6ea9bf54f98f5c88184f6a735dda63024f3b0c0749441f0baa70



(press <Enter> as much as you like, wait as long as you like, no changes)


```

The terminal hangs at this point without the process completing. On pressing `<CTRL-C>`:

```
^C[2024-03-29T20:59:33Z INFO  blue_build::commands::build] Recieved SIGINT, cleaning up build...
```
#### Expected Behavior

The `bluebuild build` command should exit gracefully (return `exit 0` or similar) and restore control of the shell to the user.

#### Additional context/Screenshots

The report below was generated from inside of the [bluebuild cli distrobox image](https://github.com/blue-build/cli?tab=readme-ov-file#distrobox) using `bluebuild bug-report`.

#### Possible Solution

N/A

#### Environment
- Blue Build Version: 0.8.1
- Operating system: Fedora 38.0.0
- Branch/Tag:  ()
- Git Commit Hash: 

#### Shell
- Name: bash 
- Version: GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Terminal emulator: <unknown terminal> <unknown version>

#### Rust
- Rust Version: rustc 1.76.0 (07dca489a 2024-02-04)
- Rust channel: 1.76.0-x86_64-unknown-linux-gnu release
- Build Time: 2024-02-26 14:49:06 +00:00

#### Recipe:

This issue has happened on all of my custom recipes, but here is one particular example:

```yml
name: sway
description: sway image based on sericiea
base_image: ghcr.io/ublue-os/sericea-main
image_version: '39'
blue_build_tag: null
modules:
- type: files
  files:
  - usr: /usr
- type: akmods
  install: null
- type: rpm-ostree
  repos:
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
  install:
  - sddm
  - sddm-themes
  - nwg-shell
  - aylurs-gtk-shell
  - swww
  - waypaper
  - adwaita-qt5
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme
  - papirus-icon-theme
  - fuzzel
  - xorg-x11-server-Xwayland
  - polkit
  - lxpolkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - gnome-keyring
  - pavucontrol
  - playerctl
  - qt5ct
  - qt5-qtwayland
  - qt6-qtwayland
  - xlsclients
  - vulkan-validation-layers
  - vulkan-tools
  - google-noto-emoji-fonts
  - gnome-disk-utility
  - fcitx5
  - wireplumber
  - pipewire
  - pamixer
  - mpd
  - ncmpcpp
  - sox
  - network-manager-applet
  - NetworkManager-openvpn
  - NetworkManager-openconnect
  - bluez
  - bluez-tools
  - blueman
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - xarchiver
  - imv
  - p7zip
  - unrar-free
  - gvfs-smb
  - dolphin
  - slurp
  - grim
  - wf-recorder
  - wlr-randr
  - wlsunset
  - grimshot
  - light
  - swaybg
  - swaylock
  - swayidle
  - kanshi
  - kitty
  - foot
  - xfce4-terminal
  - mpv
  - tailscale
  - tmux
  - screen
  - pass
  - pass-otp
  - qemu-kvm
  - libvirt-daemon
  - libvirt-daemon-config-network
  - libvirt-daemon-driver-interface
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nwfilter
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-kvm
  - libvirt-client
  - virt-install
  - virt-manager
- type: fonts
  fonts:
    nerd-fonts:
    - Iosevka
    - FiraCode
    - Hack
    - SourceCodePro
    - Terminus
    - JetBrainsMono
    - NerdFontsSymbolsOnly
- type: script
  scripts:
  - settheming.sh
- type: default-flatpaks
  user:
    install:
    - org.gtk.Gtk3theme.adw-gtk3
    - org.gtk.Gtk3theme.adw-gtk3-dark
    - org.mozilla.firefox
- type: signing
- type: systemd
  system:
    enabled:
    - tailscaled.service
    - libvirtd.service
- type: rpm-ostree
  repos:
  - https://copr.fedorainfracloud.org/coprs/tofik/sway/repo/fedora-%OS_VERSION%/tofik-sway-fedora-%OS_VERSION%.repo
  install:
  - swaync

```
