### ISSUE TITLE
arriving at a stable, functional, and sensical recipe standard

### ISSUE THREAD

**Issue by xynydev** [blue-build/cli#180]
(this issue is filed under CLI, because this is the only place changes would have to be made to implement changes to the recipe format)

_I had an epiphany._ But let me preface a bit; if the purpose of the _recipe_ is to be a versatile standard that describes the build and publish process of a native container image, is it as good as that as can be? And if not, aren't we in the _broad_ ideal moment of time to evolve it?

Here's how it _could_ look:
```yaml
base-image:
    url: ghcr.io/ublue-os/silverblue-main
    tag: 40
    public-key: https://... # unimplemented, needed for base image verification, would be optional, and automatically supplied for ublue etc.
    type: ostree # unimplemented, might be needed for effectively supporting different base images, which might need things like running `ostree container commit` 
result-image:
    name: weird-os
    description: This is my personal OS image.
    tags: # replaces the "latest" and timestamp tags
       - gts
stages:
    ...
modules:
    ...
```

That's a sketch, but IMO it's already better than what we have now. Ideas and discussion appreciated here, though.

Multiple versions of the recipe standard could be supported in a way similar to other projects, say, [`docker-compose.yml`](https://stackoverflow.com/questions/76156527/what-does-the-first-line-in-the-docker-compose-yml-file-that-specifies-the-ve) do. I'd opt for using the `$schema:` key to specify the version; that would force us to supply jsonschema for all supported versions, and the user to update both the autocomplete source and the actual version in their recipes at the same time. This would set a solid foundation for breaking recipe changes in the future. If rust can do jsonchema validation, maybe we could even get multi-version support in CLI with not much extra effort?

**Comment by fiftydinar** [comment]
Generally looks good.

```yaml
    tags: # replaces the "latest" and timestamp tags
       - gts
```

I'm interested in this part.

It would be possible to provide multiple tags, like `gts` & `latest`, right?

What about other images, like VanillaOS, which have different release schedules?
I guess that only `latest` would be supplied, while `gts` is more of a Fedora/Universal Blue thing.

**Comment by xynydev** [comment]
Yes, that's an already implemented feature, and can be used to set any set of custom tags on any image. `latest` is added automatically if `tags` isn't set, but after that, it's up to the user.

**Comment by gmpinder** [comment]
I think this structure makes way more sense TBH. I do think that `result-image:` could be something else like `final-image` or `main-image`. The public key property is a good addition too. I was envisioning adding our own labels onto images that would be a link to the public key or something like that. This way we would be able to pull that information dynamically on build. But this property would be perfect for images that aren't built by `bluebuild`.

**Comment by gmpinder** [comment]
Something else that could probably be added later for the user's image is `labels:` which would just be a map

**Comment by gmpinder** [comment]
As for the "schema" for the recipe, the struct definitions and the use of serde already act like a schema enforcer. However, I think using schema's for the configuration of modules would be a really good idea to be able to validate the input before building.

**Comment by gmpinder** [comment]
So there is a [jsonschema](https://crates.io/crates/jsonschema) crate that we can use that is being actively maintained it would seem. Also we could include a tool to convert user's recipes using [struct-convert](https://crates.io/crates/struct-convert). I used this at work for helping to create a helm values migration tool for deploying our services.

**Comment by gmpinder** [comment]
> ```yaml
> base-image:
>     url: ghcr.io/ublue-os/silverblue-main
> ```

Just realized. I don't think this should be `url:`. Image refs are their own separate standard from URL. Maybe `name`, `from`, `image-name`, `ref`. I just think URL is misleading a bit.

**Comment by xynydev** [comment]
> > ```yaml
> > base-image:
> >     url: ghcr.io/ublue-os/silverblue-main
> > ```
> 
> Just realized. I don't think this should be `url:`. Image refs are their own separate spec from URL. Maybe `name`, `from`, `image-name`, `ref`. I just think URL is misleading a bit.

Yeah I was a bit iffy on that too, but don't know what would be better. `from` isn't that clear either IMO. `ref` could be? Will have to see how it's referred to in the spec.

**Comment by xynydev** [comment]
> I do think that result-image: could be something else like `final-image` or `main-image`. 

Maybe `final-image` then, definetly not `main-image`, that's an overloaded term. `metadata` would be another possible key name for it.

**Comment by gmpinder** [comment]
> Maybe `final-image` then, definetly not `main-image`, that's an overloaded term. `metadata` would be another possible key name for it.

I like `metadata`. Feels k8s-ish

**Comment by fiftydinar** [comment]
`final-image` is better imo, `metadata` can be referred to almost anything that contains information.

**Comment by xynydev** [comment]
To spin that argument around: basically everything in the recipe concerns 'the final image', while `metadata` would quite literally be the final images *metadata*, as in it's name, description, labels, etc.

**Comment by CarrotManMatt** [comment]
Could you do a combination? `final-image-metadata` or is that a bit waffly?

**Comment by xynydev** [comment]
That is a bit "waffly" IMO yeah 😅

**Comment by gmpinder** [comment]
So it's sounding like it's going to be something like this?

```yaml
base-image:
    ref: ghcr.io/ublue-os/silverblue-main:40
    public-key: https://... # unimplemented, needed for base image verification, would be optional, and automatically supplied for ublue etc.
    type: ostree # unimplemented, might be needed for effectively supporting different base images, which might need things like running `ostree container commit` 
final-image:
    name: weird-os
    description: This is my personal OS image.
    tags: # replaces the "latest" and timestamp tags
       - gts
stages:
    ...
modules:
    ...
```

I think combining the `tag` in with `ref` makes things a little clearer especially since we aren't building FROM multiple tagged images

**Comment by xynydev** [comment]
`ref` is still unclear IMO, not sure what it could be instead, though. I think the reason I did it like this is to (1) possibly support matrixing with a single recipe in the future and (2) that the diffs when changing the version would look nicer. 

But yeah, I probably agree that this is better.

**Comment by gmpinder** [comment]
How about something like:

```yaml
base-image:
    image: ghcr.io/ublue-os/silverblue-main:40
    public-key: https://... # unimplemented, needed for base image verification, would be optional, and automatically supplied for ublue etc.
    type: ostree # unimplemented, might be needed for effectively supporting different base images, which might need things like running `ostree container commit` 
```

It feels a bit redundant, but it follows convention from k8s and docker compose. Maybe if we want, we can find another name for `base-image`.

**Comment by xynydev** [comment]
```yaml
base:
  image: ghcr.io/ublue-os/silverblue-main:40
  public-key: https://... # unimplemented, needed for base image verification, would be optional, and automatically supplied for ublue etc.
  type: ostree # unimplemented, might be needed for effectively supporting different base images, which might need things like running `ostree container commit` 
metadata:
  name: weird-os
  description: ...
  tags: [gts]
stages:
  ...
modules:
  ...
```

**Comment by gmpinder** [comment]
I'm liking that

**Comment by gmpinder** [comment]
Something that I think would be super useful. I've been looking through how the Bluefin `Containerfile` is laid out and it gave me the idea of having something like:

```yaml
base:
  from-recipe: parent-recipe.yml
...
```

This could allow building tiered images like how bluefin and bluefin-dx are created.

```dockerfile
FROM ${BASE_IMAGE}:${FEDORA_MAJOR_VERSION} AS base
# ...

FROM base AS dx
# ...
```

We could then build and push both in a single build process (once I figure that out).
