### ISSUE TITLE
test_template

### ISSUE THREAD

**Issue by akarui-hikarii** [blue-build/cli#31]
#### Environment
- Blue Build Version: v
pkg_version:0.5.5
branch:bugreport-command
commit_hash:
build_time:1980-01-01 00:00:00 +00:00
build_env:rustc 1.75.0 (82e1608df 2023-12-21),stable-x86_64-unknown-linux-gnu
- Operating system: Fedora 39.0.0
- Git Commit Hash: 
- Branch/Tag: bugreport-command

#### Shell
- Name: bash 
- Version: GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Terminal emulator: <unknown terminal> <unknown version>

#### Rust
- Rust Version: rustc 1.75.0 (82e1608df 2023-12-21)
- Rust channel: stable-x86_64-unknown-linux-gnu release
- Build Time: 1980-01-01 00:00:00 +00:00

#### Recipe:
```
---
name: orora
description: custom image for me. Using XFCE4 and Hyprland

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/vauxite-asus
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - neovim
      - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
```
