### ISSUE TITLE
iso installation error: Pathname can't be converted from UTF-8 to current locale

### ISSUE THREAD

**Issue by white-gecko** [blue-build/cli#310]
When I generate an iso from my image, and try to install it, the installation breaks after a while with the message:

> The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=/run/install/repo/bluejay-latest --transport=oci --no-signature-verification' exited with the code 1.

When I open the shell with ctrl-alt-f2 and look into `/tmp/packaging.log` I find the actual error to be:

> error: Pathname can't be converted from UTF-8 to current locale

This is probably the same issue as reported here: https://github.com/JasonN3/build-container-installer/issues/150

Since I experience this issue specifically with `bluebuild generate-iso` but I don't understand the details about the maybe missing env var and if this issue is specific to bluebuild, as pointed out in this comment: https://github.com/JasonN3/build-container-installer/issues/150#issuecomment-2543230531 I just feel free to report the issue here ;-)

**Comment by blueniri** [comment]
Just ran into this as well. I was stepping through the tutorial (https://blue-build.org/how-to/generate-iso/), generated the ISO, and am running into this. This was with the default out-of-the-box generated recipe; zero customization.

When running in a VM to test, the installation eventually fails with: 

```
Pathname can't be converted from UTF-8 to current locale.
```
![Screenshot_20241223_155659](https://github.com/user-attachments/assets/cf50ca39-b51d-42da-8a2b-4f8ec6c2210c)

I changed the base image to see if it made a difference, but it didn't. Same error.

Recipe.yml:

```
---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue-niri-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

```
