### ISSUE TITLE
test_template_#2

### ISSUE THREAD

**Issue by akarui-hikarii** [blue-build/cli#33]
#### Environment
- Blue Build Version: 0.5.5
- Operating system: Fedora 39.0.0
- Branch/Tag: bugreport-command (v0.5.5)
- Git Commit Hash: 16d4e1c9b066786df4daccbcedd524c8342975f2

#### Shell
- Name: bash 
- Version: GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Terminal emulator: <unknown terminal> <unknown version>

#### Rust
- Rust Version: rustc 1.77.0-nightly (6b4f1c5e7 2024-01-27)
- Rust channel: nightly-x86_64-unknown-linux-gnu release
- Build Time: 1980-01-01 00:00:00 +00:00
#### Recipe:
```yml
---
from_file: common.yml
type: files
  files:
  - homedir: /usr/etc/homedir
  - usr: /usr

type: files
  files:
  - usr: /usr

type: rpm-ostree
  repos:
  - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  install:
  - neovim
  - starship
  remove:
  - firefox
  - firefox-langpacks

type: default-flatpaks
  notify: true
  system:
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub
    install: null
    remove: null
  user:
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub

type: script
  scripts:
  - signing.sh
```
