### ISSUE TITLE
Installation of an rpm from gitlab fails on DNS resolution error

### ISSUE THREAD

**Issue by thrix** [blue-build/cli#398]
#### Current Behavior
I am not able to install https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm, the build fails with:

```
g.i/t/workstaton:latest => Downloading https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm...failed
g.i/t/workstaton:latest => error: Handling argument https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm: error sending request for url (https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm): client error (Connect): dns error: failed to lookup address information: Temporary failure in name resolution: failed to lookup address information: Temporary failure in name resolution
```

#### Expected Behavior
Building works. On the same machine I can curl the file just well:

```
❯ curl -I https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm
HTTP/2 200 
date: Wed, 26 Mar 2025 23:51:12 GMT
content-type: application/octet-stream
content-length: 1276259
cf-ray: 926a8dfc69d0246f-PRG
cf-cache-status: HIT
accept-ranges: bytes
age: 3
cache-control: max-age=60, public, must-revalidate, stale-while-revalidate=60, stale-if-error=300, s-maxage=60
content-disposition: attachment
etag: "9dc1867bcb6e96cecd2db0c3d1affb17"
strict-transport-security: max-age=31536000
vary: Accept
content-security-policy: base-uri 'self'; child-src https://www.google.com/recaptcha/ https://www.recaptcha.net/ https://www.googletagmanager.com/ns.html https://*.zuora.com/apps/PublicHostedPageLite.do https://gitlab.com/admin/ https://gitlab.com/assets/ https://gitlab.com/-/speedscope/index.html https://gitlab.com/-/sandbox/ 'self' https://gitlab.com/assets/ blob: data:; connect-src 'self' https://gitlab.com wss://gitlab.com https://sentry.gitlab.net https://new-sentry.gitlab.net https://customers.gitlab.com https://snowplow.trx.gitlab.net https://sourcegraph.com https://collector.prd-278964.gl-product-analytics.com snowplowprd.trx.gitlab.net; default-src 'self'; font-src 'self'; form-action 'self' https: http:; frame-ancestors 'self'; frame-src https://www.google.com/recaptcha/ https://www.recaptcha.net/ https://www.googletagmanager.com/ns.html https://*.zuora.com/apps/PublicHostedPageLite.do https://gitlab.com/admin/ https://gitlab.com/assets/ https://gitlab.com/-/speedscope/index.html https://gitlab.com/-/sandbox/; img-src 'self' data: blob: http: https:; manifest-src 'self'; media-src 'self' data: blob: http: https:; object-src 'none'; report-uri https://new-sentry.gitlab.net/api/4/security/?sentry_key=f5573e26de8f4293b285e556c35dfd6e&sentry_environment=gprd; script-src 'strict-dynamic' 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ https://apis.google.com https://*.zuora.com/apps/PublicHostedPageLite.do 'nonce-oXC3UYpSY7ThNeG+6m/Omg=='; style-src 'self' 'unsafe-inline'; worker-src 'self' https://gitlab.com/assets/ blob: data:
gitlab-lb: haproxy-main-56-lb-gprd
gitlab-sv: web-gke-us-east1-c
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-gitlab-meta: {"correlation_id":"01JQABXPFNPH5XMGYFAFRZ30S3","version":"1"}
x-permitted-cross-domain-policies: none
x-request-id: 01JQABXPFNPH5XMGYFAFRZ30S3
x-runtime: 0.132015
x-ua-compatible: IE=edge
x-xss-protection: 1; mode=block
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=vZ4nqpCPftLm%2BhhyixSDklOJKCCDAPo2i7fBhNHG4XAuSwa6tw32US8HGoHs6ZoL0eI22mWo3UevrP62c1SDZYsHHsp06cjkukt41p8meDPvX0yEWUC%2BeZwHc21STNI0CFwR1BhrSHo%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
set-cookie: _cfuvid=sGbEmM7jVCb.uEbwO9a2JHUNejtk6CTUm98vGVLxhcU-1743033072086-0.0.1.1-604800000; path=/; domain=.gitlab.com; HttpOnly; Secure; SameSite=None
server: cloudflare
```

#### Additional context/Screenshots
I wanted to enable `--network=host` but no idea how to do it.

#### Possible Solution
N/A

#### Environment
- Blue Build Version: 0.9.8
- Operating system: Fedora 41.0.0
- Branch/Tag:  (v0.9.8)
- Git Commit Hash: 6a5f54b2fd863c99ba599b7a9e36bced29cbb38f

#### Shell
- Name: bash 
- Version: GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Terminal emulator: <unknown terminal> <unknown version>

#### Rust
- Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
- Rust channel:  release
- Build Time: 2025-02-12 19:16:40 +00:00

#### Recipe:
```yml
name: workstaton
description: Thrix's workstation
base_image: ghcr.io/ublue-os/sericea-main
image_version: latest
modules:
- type: rpm-ostree
  install:
  - fontawesome-fonts-all
  - mate-polkit
  - nautilus
  - https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm
  - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  optfix:
  - google
  - smfp-common
- type: bling
  install:
  - rpmfusion
  - '1password'
- type: files
  files:
  - source: system
    destination: /
- type: script
  snippets:
  - update-ca-trust
  - rm -f /usr/share/wireplumber/scripts/node/suspend-node.lua
- type: systemd
  system:
    enabled:
    - systemd-timesyncd
```
